package com.software.cafejariapp.presentation.util

sealed class Screen(val route: String) {
    object MasterRoomScreen: Screen("master_room_screen")
    object MapScreen: Screen("home_screen")
    object ProfileScreen: Screen("profile_screen")
    object PointHistoryScreen: Screen("point_history_screen")
    object ProfileEditScreen: Screen("profile_edit_screen")
    object ShopScreen: Screen("shop_screen")
    object ShoppingBagScreen: Screen("shopping_bag_screen")
    object LoginScreen: Screen("login_screen")
    object RegisterScreen: Screen("register_screen")
    object ResetScreen: Screen("reset_screen")
    object AuthScreen: Screen("auth_screen")
    object SplashScreen: Screen("splash_screen")
    object GuideListScreen: Screen("guide_list_screen")
    object EventScreen: Screen("event_screen")
    object FaqScreen: Screen("faq_screen")
    object LeaderBoardScreen: Screen("leaderboard_screen")
    object RegisterCafeScreen: Screen("register_cafe_screen")
    object ProfileKalendarScreen: Screen("profile_kalendar_screen")
    object InquiryScreen: Screen("inquiry_screen")
    object PointResultScreen: Screen("point_result_screen")
    object CheckLoginScreen: Screen("check_login_screen")
    object PermissionScreen: Screen("permission_screen")
    object UpdateScreen: Screen("update_screen")
    object WebViewScreen: Screen("web_view_screen")
    object RegisterCafeResultScreen: Screen("register_cafe_result_screen")
    object InquiryAnswerScreen: Screen("inquiry_answer_screen")
    object ModifyAdditionalCafeInfoScreen: Screen("modify_additional_cafe_info_screen")
}
